### ISSUE TITLE
What's up with this fork?

### ISSUE THREAD

**Issue by A248** [Matocolotoe/Skript-1.8#4]
This repository has 6 commits. Skript has way more. From the looks of it, you're deleting / re-committing the repository every time there is an update.

Can't this be changed? I'm sure there is a better way. What happened with merge commits and PRs?

**Comment by Matocolotoe** [comment]
I just made a new Discord server and repository since the old ones were really dirty and many errors had been made about updates.

When there is an update, I just download the source code of the original plugin and I copy it in the Skript-1.8 folder, and... I just push the changes and release the new plugin ?

However I don't understand why the number of commits compared to Skript would be a problem.

**Comment by A248** [comment]
It's not that the number of commits is a problem; that doesn't matter. The number of commits merely indicated to me that you were copying the entire source on every update.

I'm wondering why you don't just pull the changes from Skript to your repository instead of downloading the entire source every time. You wouldn't have to re-do all of your changes to make Skript compatible with 1.8.

**Comment by Matocolotoe** [comment]
Doesn't take much time, and some files have to stay as they currently are not to break the entire plugin. Maybe I should try that indeed some day ^^

**Comment by A248** [comment]
There's just 1 slight problem I noticed. Since this technically isn't a fork of Skript according to Github, you can't just create a new PR and pull from the Skript repo. You may want to consider re-forking, as ironic as it seems.

**Comment by Matocolotoe** [comment]
For now, I'll stick with what I do, even if it takes a little too much time ^^
